### ISSUE TITLE
[Request] Please allow config to enable/disable individual features

### ISSUE THREAD

**Issue by dragonmcmx1** [remiX-/QualityCompany#1]
I love some of the features of this mod like being able to see the value of held items and shotgun ammo, but other things like the monitor display clash with other mods such as GeneralImprovements' better monitors. The ability to disable features individually would be greatly appreciated!

**Comment by JustinHZAP** [comment]
> I love some of the features of this mod like being able to see the value of held items and shotgun ammo, but other things like the monitor display clash with other mods such as GeneralImprovements' better monitors. The ability to disable features individually would be greatly appreciated!

This is planned for a future update. Thank you for your request.

**Comment by JustinHZAP** [comment]
Hi, thank you for request.

We are planning this for a future update. Thanks!

**Comment by remiX-** [comment]
Hey @dragonmcmx1, thanks for this. This is now a part of 1.2.0.
We will always be looking into having better compatibility with other mods.

We also need to look into GeneralImprovements' Inventory config for "PickupInOrder" and "RearrangeOnDrop" as I noticed that causes desync with the re-arranged items old values not updating.

**Comment by remiX-** [comment]
@dragonmcmx1 Hey, we should have better mod compatibility with GeneralImprovements now in v1.2.1 with some additional config for forcing refreshing the UI entirely. It is disabled by default.
