### ISSUE TITLE
GeneralImprovements mod bugs some labels

### ISSUE THREAD

**Issue by NilaierMusic** [remiX-/QualityCompany#11]
With options such as `PickupInOrder`, `RearrangeOnDrop` and `TwoHandedInSlotOne` set to `true` from [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements), QualityCompany's labels either fail to display on some items, or stay there, even if items have been dropped already.

![image](https://github.com/remiX-/QualityCompany/assets/86863646/75e75c3a-04e1-463e-8ea2-b89223dbe324)
![Lethal_Company_aiVBHsBR6Y](https://github.com/remiX-/QualityCompany/assets/86863646/6fb76e79-7e12-46b3-9bdf-dd6bb22ecba1)

**Comment by remiX-** [comment]
Hey @NilaierMusic 

Can you see if enabling `InventoryForceUpdateAllSlotsOnDiscard` fixes this?

**Comment by NilaierMusic** [comment]
Setting `ForceUpdateAllSlotsOnDiscard` to `true` seems to fix the label ghosting issue, but it still doesn't fix other issues like shotguns not having any labels when you first pick them up in your ship after reloading the game or UI elements shifting to weird places after hopping through different saves.
![Lethal_Company_5k5gYBuC07](https://github.com/remiX-/QualityCompany/assets/86863646/37be6bf2-29e0-4f27-a902-97bc30042839)

**Comment by JustinHZAP** [comment]
> With options such as `PickupInOrder`, `RearrangeOnDrop` and `TwoHandedInSlotOne` set to `true` from [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements), QualityCompany's labels either fail to display on some items, or stay there, even if items have been dropped already.

The problem here is that GeneralImprovements does not use base game "methods" of moving items around on the HUD, they are doing it in a sort of "behind the scenes" way. This makes their mod more unfriendly to base game hooks. However we try to accommodate these type of things in QualityCompany.

> Setting ForceUpdateAllSlotsOnDiscard to true seems to fix the label ghosting issue, but it still doesn't fix other issues like shotguns not having any labels when you first pick them up in your ship after reloading the game or UI elements shifting to weird places after hopping through different saves.

There is a delay configuration, QualityCompany waits for HUD modifications to be applied before initializing which may cause this issue if you try to pick up items before this delay, the inventory may be initialized unexpectedly. We will look into improving this as we develop the mod.

**Comment by remiX-** [comment]
@NilaierMusic It's a bit unfortunate that GeneralImprovements shuts off all other monitor texts other than its' own. Any chance anyone has logged this on their end?

![image](https://github.com/remiX-/QualityCompany/assets/2831747/4e6cd142-9071-457e-a730-5387dfbcb449)

**Comment by remiX-** [comment]
Closing this for now as there have not been any more updates and not being able to reproduce on our side.

Please re-open or log a new issue if the issue arises again 😄
