### ISSUE TITLE
[Bug] >qc command duplicates when reloading save

### ISSUE THREAD

**Issue by dragonmcmx1** [remiX-/QualityCompany#13]
When exiting to the main menu and loading back into any save, the > qc indicator in the terminal menu duplicates. This can be repeated multiple times.

![image](https://github.com/remiX-/QualityCompany/assets/155202666/4ec349e7-fa88-4393-bb19-49ff678303a1)

Also, the qc command appears even if all terminal related features are disabled. Could you add an option to disable the qc command as well to avoid cluttering the terminal unnecessarily?

**Comment by remiX-** [comment]
Hey @dragonmcmx1,

That was a bit of a silly on my part xD This should be solved in 1.3.4
