### ISSUE TITLE
Conflicts with AccurateStaminaDisplay

### ISSUE THREAD

**Issue by WGrav01** [remiX-/QualityCompany#16]
Rather self-explanatory, AccurateStaminaDisplay does not affect the stamina bar while QualityCompany is active.

**Comment by remiX-** [comment]
Will have a look at this tomorrow - sounds rather interesting as we definitely don't affect the Stamina at all

**Comment by WGrav01** [comment]
Sorry, it actually doesn’t, config files got changed without my knowledge
so AccurateStaminaDisplay was off.
