### ISSUE TITLE
PatchFixScanEnabled incompatibility with LethalLevelLoader

### ISSUE THREAD

**Issue by Agitatio** [remiX-/QualityCompany#18]
Having `PatchFixScanEnabled` set to `true` makes `scan` command show moons list when QC and LLL are both installed.

**Comment by remiX-** [comment]
Hey @Agitatio,

This is an issue with LLL itself, you can find more info on this issue and the mod owner is aware of it :)

https://github.com/IAmBatby/LethalLevelLoader/issues/54#issuecomment-1963125520
