### ISSUE TITLE
[Suggestion] Add an active update option

### ISSUE THREAD

**Issue by TheBlackEntity** [remiX-/QualityCompany#22]
It would be nice if QualityCompany had an option to update the hotbar actively.

This would fix some issues, like the scrap value not updating after the  `GamblingMachineAtTheCompany` mod changed it

**Comment by remiX-** [comment]
Hey @TheBlackEntity,

I have added this as a configurable option in v1.5.0 😄 

It's disabled by default and if enabled, will update every second.
