### ISSUE TITLE
The price is stuck in the slot

### ISSUE THREAD

**Issue by Paradox75831004** [remiX-/QualityCompany#3]
The old price is kept on top of the empty slot. I don't know about ReservSlot, but should I check with them too, or does it not apply to them?

Assembly Code - 018d7d54-66dc-0462-5b2e-f96ccee9a0a9

![image](https://github.com/remiX-/QualityCompany/assets/72872478/3ccfced9-399c-4e86-89c3-e3a427a9ad94)

**Comment by Paradox75831004** [comment]
Errors disappear - if you take items on top and reset them, but it doesn't work with all of them (I mean with custom ones)

**Comment by Paradox75831004** [comment]
![image](https://github.com/remiX-/QualityCompany/assets/72872478/9830b5fa-306f-40f1-8086-9406cc18beeb)
Reserve slot is indulging, but not critically.It's just that the picture in the gun freezes

**Comment by remiX-** [comment]
Hey @Paradox75831004, thanks for bringing this up.

Yep, we have noticed a similar issue in conjunction with mods that alter players' inventory in specific ways. Is the only mod doing this, in your case, the reserved item slots mods, or do you have other mods that possibly do this as well such as GeneralImprovements inventory settings?

We're going to look into having compatibility with GeneralImprovements which then in turn should solve this too if this is occurring with other mods as well :)

**Comment by remiX-** [comment]
Hey @Paradox75831004.

This should be sorted in v1.2.1 :)
